package dal

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

type GroupsDao struct {
	Ds *DataStore
}

func (dao *GroupsDao) GetGroupsEx() (res []*GroupEx, err error) {
	sql := `select g.*,  
		(select count(*) from tasks where g_id=g.g_id) as tasks_count 
		from groups g`
	errMap := make(map[string]int)
	onDto := func(row map[string]interface{}) {
		obj := GroupEx{}
		fromRow(&obj.GId, row, "g_id", errMap)
		fromRow(&obj.GName, row, "g_name", errMap)
		fromRow(&obj.TasksCount, row, "tasks_count", errMap)
		res = append(res, &obj)
	}
	err = dao.Ds.QueryAllRows(sql, onDto)
	if err == nil {
		err = errMapToErr(errMap)
	}
	return
}

func (dao *GroupsDao) GetGroupsIds() (res []int64, err error) {
	sql := `select g.*,  
		(select count(*) from tasks where g_id=g.g_id) as tasks_count 
		from groups g`
	errMap := make(map[string]int)
	onRow := func(val interface{}) {
		var data int64
		fromVal(&data, val, errMap)
		res = append(res, data)
	}
	err = dao.Ds.QueryAll(sql, onRow)
	if err == nil {
		err = errMapToErr(errMap)
	}
	return
}

func (dao *GroupsDao) GetGroupsId() (res int64, err error) {
	sql := `select g.*,  
		(select count(*) from tasks where g_id=g.g_id) as tasks_count 
		from groups g`
	r, err := dao.Ds.Query(sql)
	if err == nil {
		err = assign(&res, r)
	}
	return
}
