package dal

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

type GroupEx struct {
	GId        int64  `json:"g_id"` // PK
	GName      string `json:"g_name"`
	TasksCount int64  `json:"tasks_count"`
}
