package dbal

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

import "sdm_demo_gorm_todolist/models"

type TasksDao struct {
	ds DataStore
}

// (C)RUD: tasks
// Generated values are passed to DTO/model.

func (dao *TasksDao) CreateTask(p *models.Task) (err error) {
	err = dao.ds.Create("tasks", p)
	return
}

// C(R)UD: tasks

func (dao *TasksDao) ReadTaskList() (res []*models.Task, err error) {
	err = dao.ds.ReadAll("tasks", res)
	return
}

// C(R)UD: tasks

func (dao *TasksDao) ReadTask(tId int64) (res *models.Task, err error) {
	res = &models.Task{}
	err = dao.ds.Read("tasks", res, tId)
	return
}

// CR(U)D: tasks
// Returns the number of affected rows or -1 on error.

func (dao *TasksDao) UpdateTask(p *models.Task) (res int64, err error) {
	res, err = dao.ds.Update("tasks", p)
	return
}

// CRU(D): tasks
// Returns the number of affected rows or -1 on error.

func (dao *TasksDao) DeleteTask(p *models.Task) (res int64, err error) {
	res, err = dao.ds.Delete("tasks", p)
	return
}
