package dao

import "sdm_demo_gorm_todolist/dal"

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

type GroupsDao struct {
	ds DataStore
}

func (dao *GroupsDao) GetGroupsEx() (res []*dal.GroupEx, err error) {
	sql := `select g.*,  
		(select count(*) from tasks where g_id=g.g_id) as tasks_count 
		from groups g`
	errMap := make(map[string]int)
	onDto := func(row map[string]interface{}) {
		obj := dal.GroupEx{}
		fromRow(&obj.GId, row, "g_id", errMap)
		fromRow(&obj.GName, row, "g_name", errMap)
		fromRow(&obj.TasksCount, row, "tasks_count", errMap)
		res = append(res, &obj)
	}
	err = dao.ds.QueryAllRows(sql, onDto)
	if err == nil {
		err = errMapToErr(errMap)
	}
	return
}
