package models

// This code was generated by a tool. Don't modify it manually.
// Additional (hand-coded) methods can be implemented in a separate file like <this_file>_ex.go.
// http://sqldalmaker.sourceforge.net

type GroupEx struct {
	GId        int64  `json:"g_id"` // PK
	GName      string `json:"g_name"`
	TasksCount int64  `json:"tasks_count"`
}
